
rabbit1:
  image: "rabbitmq:3-management"
  hostname: "rabbit1"
  environment:
    RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15673:15672"
    - "5673:5672"
  labels:
    NAME: "rabbitmq1"
  volumes:
    - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
    - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
    - "./definitions.json:/etc/rabbitmq/definitions.json:ro"
    - "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
